apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codebase-steward.fullname" . | default "codebase-steward" }}-data-pvc
spec:
  accessModes:
    - {{ .Values.persistence.modelStorage.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.modelStorage.size | default "200Gi" }}
  {{- if .Values.persistence.modelStorage.storageClass }}
  storageClassName: {{ .Values.persistence.modelStorage.storageClass }}
  {{- end }}