apiVersion: v1
kind: Service
metadata:
  name: {{ include "codebase-steward.fullname" . }}-model-serving
spec:
  type: ClusterIP
  selector:
    app: {{ include "codebase-steward.fullname" . }}-model-serving
  ports:
    - port: {{ .Values.modelServing.port }}
      targetPort: {{ .Values.modelServing.port }}
      protocol: TCP
      name: http
