apiVersion: v1
kind: Service
metadata:
  name: {{ include "codebase-steward.fullname" . }}-model-serving
  labels:
    app: {{ include "codebase-steward.name" . }}-model-serving
spec:
  type: ClusterIP
  selector:
    app: {{ include "codebase-steward.name" . }}-model-serving
  ports:
    - name: http
      port: {{ .Values.modelServing.servicePort | default 8001 }}
      targetPort: {{ .Values.modelServing.port | default 8001 }}
