apiVersion: v1
kind: Service
metadata:
  name: codebase-steward-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: codebase-steward
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
